require("dotenv").config();
const express = require("express");
const cors = require("cors");
const connection = require("./db");
const staffRoutes = require("./routes/staffRoutes");
const itemRoutes = require("./routes/itemRoutes");
const tableRoutes = require("./routes/tableRoutes");
const customerRoutes = require("./routes/customerRoutes");
const adminRoutes = require("./routes/adminRoutes");
 const promotionsRoutes = require("./routes/promotionsRoutes");
 const reserveRoutes = require("./routes/reserveRoutes");
const orderRoutes = require("./routes/orderRoutes");
const app = express();
const PORT = process.env.PORT || 8090;
connection();
app.use(express.urlencoded({ extended: true }));
app.use(express.json());
app.use(cors());
app.use((req, res, next) => {
	res.locals.path = req.path;
	next();
});
app.use("/api/staffs", staffRoutes);
app.use("/api/items", itemRoutes);
app.use("/api/tables", tableRoutes);
app.use("/api/customers", customerRoutes);
app.use("/api/admins", adminRoutes);
app.use("/api/reserves", reserveRoutes);
app.use("/api/promotions", promotionsRoutes);
app.use("/api/orders", orderRoutes);
app.listen(PORT, () => console.log(`Listening on port ${PORT}...`));